name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleRelease
      - run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-${GITHUB_SHA::7}.apk || exit 1
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-${GITHUB_SHA::7}
          path: app/build/outputs/apk/release/app-release-*.apk
          if-no-files-found: error